### ISSUE TITLE
Request: add requirements.txt

### ISSUE THREAD

**Issue by d-w-d** [mkelley/sbsearch#15]
Instead of listing packages [here](https://github.com/Small-Bodies-Node/sbsearch/blob/master/README.md#usage), could you please maintain e.g. a `requirements.txt` file so that one could simply run `pip install -r requirements.txt`?

**Comment by mkelley** [comment]
The requirements are in `setup.py`, so all one needs to do is `pip install .` in the repo, or `pip install git+https://github.com/Small-Bodies-Node/sbsearch`.  If I'm missing something there, let me know.

**Comment by d-w-d** [comment]
OK, nevermind. First time I ran `python3 setup.py install` on my system I got an error. But after creating and activating a virtualenv, it works fine. Thanks.
